### ISSUE TITLE
Icon pack support?

### ISSUE THREAD

**Issue by TobiasDev** [WeAreFairphone/FP2-Launcher#26]
I honestly love how fast and responsive this launcher is. But for me customization is one of the most important aspects of Android. (Me personally so maybe I'm the only one that cares). But I would love to use icon packs with the launcher, change single icons and the icon size.

**Comment by Roboe** [comment]
Hi! Thank you for your suggestion.

I'm a big fan of customization, too, but our efforts are currently focused on respecting the original experience for the moment. We are still fixing bugs derivated from making the launcher standalone and compatible with all devices (it was the system launcher of a specific device).

We've not made yet a formal decision about adding new features to these apps, though. If someone wants to contribute such features, please talk to us!

I'll leave this open and tag it accordingly (once I have a computer nearby). Have a good day!

**Comment by Roboe** [comment]
Hey, @TobiasDev. @Rudloff made a good job and added support for icon packs. I'll tag a new release now and it will arrive to F-Droid in some days.
