### ISSUE TITLE
Trying to change wallpaper returns crash message

### ISSUE THREAD

**Issue by StefanBrand** [WeAreFairphone/FP2-Launcher#28]
### Steps to reproduce
1. Long press homescreen
2. Click on "Wallpaper" (the first of the 4 icons at the bottom)
3. Error message appears: "Fairphone 2 Launcher was stopped"

Here is a screenshot:

[![Screenshot_2018-06-13-13-04-38.png](https://s22.postimg.cc/f8cyuv25d/Screenshot_2018-06-13-13-04-38.png)](https://postimg.cc/image/6q3iqivml/)

I have a FP1 with Android Kitkat.

**Comment by Roboe** [comment]
Good catch, Stef. Pierre fixed it. Thanks to both of you!

**Comment by StefanBrand** [comment]
Wow that was blazingly fast!!! 🙀 Chapeau!

**Comment by Roboe** [comment]
Yeah, Pierre's seal of identity, :raised_hands::tophat:
